# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('xl', 'XL'), ('l', 'L'), ('m', 'M'), ('s', 'S')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=900, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
